name: "test"
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
        env:
          CI: true
